import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Script from "next/script";

const Main = styled.main`
  margin-top: 8rem;

  width: 100%;
  height: auto;
  min-height: 100vh;

  background-image: url("./background.svg");
  background-size: cover;
  background-position: top;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Forografie - Solární studio JJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_svg_white.svg" />
      </Head>
      <Script
        type="text/javascript"
        src="https://unpkg.com/default-passive-events"
      />

      <Navbar />

      <Main>
        <h1>Solární studio Winter Sun</h1>
      </Main>
      <Footer />
    </>
  );
}
