import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";

const Main = styled.main`
  width: 100%;
  height: auto;
  background-color: #f1f1f1;

  section.main {
    background-image: url("./background.svg");
    background-size: contain;
    background-position: top;

    height: 300vh;
  }

  div.cta {
    width: calc(100% - 16rem);
    height: auto;
    margin: auto;
    padding-top: 8rem;

    display: flex;
    flex-direction: row;
    gap: 4rem;

    .cta-image {
      position: relative;
      width: 100%;
      aspect-ratio: 3500 / 2333;
      img {
        object-fit: contain;
        border-radius: 1rem;
      }
    }
    .cta-text {
      width: 100%;

      display: flex;
      flex-direction: column;
      justify-content: space-between;

      color: #777;

      h1 {
        font-size: 3rem;
        font-weight: 700;
      }

      p {
        width: 75%;
        height: auto;
        font-size: 2rem;
        font-weight: 300;
      }

      a {
        font-size: 1.5rem;
        color: #fff;
        text-decoration: none;
        padding: 0.75rem 2.5rem;
        background-color: #f761a6;
        border-radius: 1rem;
        width: min-content;
      }
    }
  }
`;

const Hero = styled.div`
  width: 100%;
  height: 100vh;

  background: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)),
    url("/hero.jpg");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;

  display: grid;
  justify-content: center;
  align-content: center;

  .logo {
    top: 10%;
    width: 45vw;
    height: 45vw;
    position: relative;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Main>
        <Hero>
          <div className="logo">
            <Image src="/logo_svg_white.svg" fill alt="logo" priority />
          </div>
        </Hero>
        <section className="main">
          <div className="cta">
            <div className="cta-image">
              <Image src="/cta-image.jpg" fill />
            </div>
            <div className="cta-text">
              <h1>Přijďte si odpočinout do našeho nového solárního studia.</h1>
              <p>
                Zažijte dokonalé opálení a získjte překrásný vzhled pokožky.{" "}
                <br />
                Navíc doplníte tělu vitamín D, který je nezbytný pro váš dobrý
                zdravotní stav.
              </p>
              <Link href="">KONTAKT</Link>
            </div>
          </div>
        </section>
      </Main>
    </>
  );
}
