import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Script from "next/script";

const Main = styled.main`
  margin: 8rem 0;

  width: 100%;
  height: auto;
  min-height: 100vh;

  background-image: url("./background.svg");
  background-size: cover;
  background-position: top;

  .cta {
    width: calc(100% - 16rem);
    @media (max-width: 1280px) {
      width: calc(100% - 8rem);
    }
    max-width: 1920px;
    height: auto;
    margin: auto;

    display: flex;
    flex-direction: row;
    @media (max-width: 900px) {
      flex-direction: column;
      width: calc(100% - 4rem);
    }
    gap: 4rem;

    .image {
      aspect-ratio: 16 / 9;
      position: relative;
      width: 100%;

      img {
        object-fit: cover;
        border-radius: 2rem;
      }
    }

    .text {
      display: flex;
      flex-direction: column;
      justify-content: space-between;

      gap: 2rem;

      width: 100%;
      h1 {
        font-size: 3rem;
      }
      p {
        color: #777;

        font-size: 1.5rem;
      }
      span {
        color: #000;
        font-weight: bold;
        white-space: nowrap;
      }
    }
  }

  .info {
    width: calc(100% - 16rem);
    margin: 6rem auto;
    @media (max-width: 1280px) {
      width: calc(100% - 8rem);
    }
    @media (max-width: 900px) {
      width: calc(100% - 4rem);
    }
    max-width: 1920px;

    color: #777;

    font-size: 1.5rem;
    span {
      color: #000;
      font-weight: bold;
      white-space: nowrap;
    }
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>O nás - Solární studio JJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_svg_white.svg" />
      </Head>
      <Script
        type="text/javascript"
        src="https://unpkg.com/default-passive-events"
      />

      <Navbar />

      <Main>
        <div className="cta">
          <div className="image">
            <Image src="/water.jpg" fill alt="cta-image water" sizes="75vw" />
          </div>
          <div className="text">
            <h1>Solární studio JJ</h1>
            <p>
              Přijďte si odpočinout do našeho nového solárního studia, zažijte
              dokonalé opálení a získejte překrásný vzhled pokožky. Navíc
              doplníte tělu <span>vitamín D</span>, který je nezbytný pro váš
              dobrý zdravotní stav. Vitamín D má vliv na stavbu kostí a tím
              působí proti osteoporóze, stimuluje imunitní systém, dále
              pozitivně ovlivňuje kožní onemocnění jako jsou lupénka nebo akné.
              Pobyt v soláriu navíc působí proti únavě a vytváří vlastní kožní
              ochranu proti agresivnímu slunečnímu záření v letních měsících.
            </p>
          </div>
        </div>
        <p className="info">
          <span>Navštivte solární studio JJ</span> a my vám připravíme{" "}
          <span>individuální opalovací plán</span> tak, abyste dosáhli zdravého,
          správného a efektivního opálení. První návštěvy byste měli absolvovat
          v kratších rozestupech, nejlépe několikrát týdně, abychom ve vaší
          pokožce probudili pigmentaci. Jakmile dosáhnete vytouženého opálení,
          postačí když přijdete jednou za týden na tzv. udržovací opalování, aby
          vaše kůže nevybledla.
        </p>
        <div className="cta">
          <div className="text">
            <h1>
              Solární studio je vybaveno špičkovými solárii značky Ergoline
            </h1>
            <p>
              <span>Ergoline</span> - je výrobce profesionálních solárií, která
              patří k nejznámějším po celém světě. Již mnoho let udává směr ve
              vývoji solárií <span>inovativní UV technologií</span>,
              průkopnickým designem, komfortem,{" "}
              <span>bezpečností opalování</span> a nadprůměrným technickým
              zpracováním. Solária Ergoline jsou osazena nejkvalitnějšími a
              nejbezpečnějšími trubicemi a jsou pravidelně servisována.
            </p>
          </div>
          <div className="image">
            <Image src="/tequila.jpg" fill alt="tequila" sizes="75vw" />
          </div>
        </div>
      </Main>
      <Footer />
    </>
  );
}
